name: Get EC2 IP Address

on:
  workflow_dispatch:
    inputs:
      ec2_instance_name:
        description: 'The name of the EC2 instance'
        required: true
      apply_changes:
        description: 'Apply changes (true/false)'
        default: 'false'

jobs:
  get-ec2-ip:
    runs-on: ubuntu-latest

    steps:
    - name: Determine Environment from EC2 Instance Name
      id: determine_env
      run: |
        EC2_INSTANCE_NAME=${{ github.event.inputs.ec2_instance_name }}
        case $EC2_INSTANCE_NAME in
          lexim-dev-bastion) ENVIRONMENT="lexim-dev" ;;
          lexim-stage-bastion) ENVIRONMENT="lexim-stage" ;;
          lexim-prod-bastion) ENVIRONMENT="lexim-prod" ;;
          tcp-dev-bastion) ENVIRONMENT="tcp-dev" ;;
          tcp-prod-bastion) ENVIRONMENT="tcp-prod" ;;
          custody-dev-bastion) ENVIRONMENT="custody-dev" ;;
          custody-stage-bastion) ENVIRONMENT="custody-stage" ;;
          dbg-dev-bastion) ENVIRONMENT="dbg-dev" ;;
          dbg-stage-bastion) ENVIRONMENT="dbg-stage" ;;
          dbg-prod-bastion) ENVIRONMENT="dbg-prod" ;;
          dau-vault-prod-bastion) ENVIRONMENT="dau-vault-prod" ;;
          lexim-prod-dxb-bastion) ENVIRONMENT="lexim-prod-dxb" ;;
          *) echo "No matching environment found for the EC2 instance name: $EC2_INSTANCE_NAME"; exit 1 ;;
        esac
        echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
        echo "Environment determined as: $ENVIRONMENT"

    - name: Set Environment Context for AWS CLI Setup
      run: |
        if [ "$ENVIRONMENT" = "lexim-dev" ]; then
          echo "Using environment: lexim-dev"
        elif [ "$ENVIRONMENT" = "lexim-stage" ]; then
          echo "Using environment: lexim-stage"
        elif [ "$ENVIRONMENT" = "lexim-prod" ]; then
          echo "Using environment: lexim-prod"
        # Add more conditions as needed for other environments
        fi

    - name: Set up AWS CLI for the determined environment
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Same secret key used for each environment
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Same secret key used for each environment
        aws-region: ${{ secrets.AWS_REGION }}  # Same region key used for each environment

    - name: Debug AWS Secrets
      run: |
        if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
          echo "AWS_ACCESS_KEY_ID is not set"
        else
          echo "AWS_ACCESS_KEY_ID is set"
        fi

    - name: Retrieve EC2 IP Address
      id: get_ip
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=${{ github.event.inputs.ec2_instance_name }}" \
          --query "Reservations[*].Instances[*].InstanceId" \
          --output text)
        if [ -z "$INSTANCE_ID" ]; then
          echo "EC2 instance with the name '${{ github.event.inputs.ec2_instance_name }}' not found"
          exit 1
        fi
        IP_ADDRESS=$(aws ec2 describe-instances \
          --instance-ids $INSTANCE_ID \
          --query "Reservations[*].Instances[*].PublicIpAddress" \
          --output text)
        echo "IP_ADDRESS=$IP_ADDRESS" >> $GITHUB_ENV

    - name: Output IP Address
      run: |
        echo "The IP address is: ${{ env.IP_ADDRESS }}"
        echo "The environment is: ${{ env.ENVIRONMENT }}"
